name: Quality Checks

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python 3.10.6
      uses: actions/setup-python@v4.2.0
      with:
        python-version: 3.10.6
    - name: Install Dependencies
      run: pip install black==22.6.0 flake8==5.0.1 isort==5.10.1 mypy==0.971 pre-commit==2.20.0
    - name: Pre-commit
      run: pre-commit run -a
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python 3.10.6
      uses: actions/setup-python@v4.2.0
      with:
        python-version: 3.10.6
    - name: Run Tests
      run: python -m unittest discover -s tests
    
